env:
  FUZZING_SERVER: autobahn
ci:
  linux:
    services: |
      autobahn:
              image: crossbario/autobahn-testsuite
              options: --name fuzzingserver
              ports:
                - 9001:9001
              volumes:
                - ${{ github.workspace }}/scripts/autobahn-config:/config
    additional_steps: |
      - name: Restart Autobahn
            # The autobahn service container is started *before* swift-websocket is checked
            # out. Restarting the container after the checkout step is needed for the
            # container to see volumes populated from the checked out workspace.
            uses: docker://docker
            with:
              args: docker restart fuzzingserver
security:
  version: 1.0.0
